# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm --version
      - run: npm install
      - run: npm run develop
        env:
          HOST: 0.0.0.0
          PORT: 337
          APP_KEYS: t+lGvXSel9RU8HAo+ORWqQ==,etFLfEYYDhz+VVvYXhiRag==,IO3EDpkQdx45dX0CtTHiAQ==,EaG0LBckjHU9mdzvt2TBEA==
          API_TOKEN_SALT: nmI2aiHLjkZiekpKROOHdQ==
          ADMIN_JWT_SECRET: MSHHcCHE+Dyz0ZGRHIzjSA==
          JWT_SECRET: JECEUQiulFCg0yT1fy9djg==

  
